name: Markdown to HTML

on:
  push:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install markdown library
        run: |
          python -m pip install --upgrade pip
          pip install markdown

      - name: Convert Markdown to HTML
        run: |
          python -c "import markdown; print(markdown.markdown(open('README.md').read()))" > README.html

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Converted README.md to README.html"
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"