name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["dev"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Copy static files
        run: |
          mkdir -p _site
          cp -r dev/GX-web/src/static/* _site/

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./_site
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
